### PR TITLE
Automatically change directory to mounted EBS volume

### LINKED ISSUE #10: submit does not automatically cd to TMPDIR when using --ebs
Observed: when using `--ebs`, the script runs in the Docker container's `WORKDIR`.
Expected: the script runs in the directory specified by `--ebs`.

### PR DESCRIPTION
**Pull request by tomazberisa**
Resolves #10

### CODE REVIEW

**Comment by brentp** [comment]
it's been a while since I looked at this code, so I'm inclined to trust you, but isn't this done by `getTmp()` ?

**Comment by tomazberisa** [comment]
It seems that getTmp() only does this when `--volumes` is specified.

**Comment by tomazberisa** [comment]
Looking into this, it seems both `--volumes` and `--ebs` are using the `$TMPDIR` env var. I'm thinking it could be useful to separate these out, e.g., `$TMPDIR_VOLUME` and `$TMPDIR_EBS`.

**Comment by tomazberisa** [comment]
i.e., something like:
https://github.com/tomazberisa/batchit/commit/47393468b9955becdeae02e543e8aa4c31e761f1

**Comment by brentp** [comment]
TMPDIR is used by the OS and things like python's tempfile or go's version to know where to make temp-files. So I'd prefer to keep it as that. I think it's fine to have one over-ride the other as the user can over-ride in their script.

**Comment by brentp** [comment]
I am fine with this PR as-is if it's ready.

**Comment by tomazberisa** [comment]
Good point re: TMPDIR and agree overrides are ok. 
Made a very minor tweak and PR is ready.
Thanks for looking into all this!

**Comment by brentp** [comment]
thanks!

**Pull request merged**
